#!/usr/bin/env python3
"""Regenerate src/Wireless/WirelessUiAsset.h from the ui/ source files.

Inlines styles.css and app.js into index.html, gzip-compresses the bundle,
and emits a PROGMEM byte array (matching the embedding style already used by
src/Fonts.cpp) plus its length. Run this after editing anything under
src/Wireless/ui/.

Usage: python3 tools/generate_wireless_ui_asset.py
"""
import gzip
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UI_DIR = ROOT / "src" / "Wireless" / "ui"
OUTPUT = ROOT / "src" / "Wireless" / "WirelessUiAsset.h"


def build_bundle() -> bytes:
	html = (UI_DIR / "index.html").read_text(encoding="utf-8")
	css = (UI_DIR / "styles.css").read_text(encoding="utf-8")
	js = (UI_DIR / "app.js").read_text(encoding="utf-8")

	html, count = re.subn(r"<!-- STYLES -->", lambda _m: css, html, count=1)
	if count != 1:
		raise SystemExit("index.html: STYLES placeholder not found")
	html, count = re.subn(r"<!-- SCRIPT -->", lambda _m: js, html, count=1)
	if count != 1:
		raise SystemExit("index.html: SCRIPT placeholder not found")
	return html.encode("utf-8")


def to_c_array(data: bytes, name: str) -> str:
	lines = []
	for i in range(0, len(data), 20):
		chunk = data[i:i + 20]
		lines.append("\t" + ", ".join(str(b) for b in chunk) + ",")
	body = "\n".join(lines)
	return (
		f"static const uint8_t {name}[] PROGMEM = {{\n{body}\n}};\n"
	)


def main() -> None:
	bundle = build_bundle()
	compressed = gzip.compress(bundle, compresslevel=9, mtime=0)

	header = []
	header.append("// Generated by tools/generate_wireless_ui_asset.py — do not edit by hand.")
	header.append("// Source: src/Wireless/ui/{index.html,styles.css,app.js}")
	header.append("#ifndef JAYD_WIRELESS_UI_ASSET_H")
	header.append("#define JAYD_WIRELESS_UI_ASSET_H")
	header.append("")
	header.append("#include <pgmspace.h>")
	header.append("#include <stddef.h>")
	header.append("#include <stdint.h>")
	header.append("")
	header.append("namespace WirelessUi {")
	header.append("")
	header.append(f"static constexpr size_t HTML_GZ_LEN = {len(compressed)};")
	header.append(f"static constexpr size_t HTML_RAW_LEN = {len(bundle)};")
	header.append("")
	header.append(to_c_array(compressed, "HTML_GZ"))
	header.append("}")
	header.append("")
	header.append("#endif")
	header.append("")

	OUTPUT.write_text("\n".join(header), encoding="utf-8")
	print(f"wrote {OUTPUT.relative_to(ROOT)}")
	print(f"raw bundle:        {len(bundle)} bytes")
	print(f"gzip compressed:   {len(compressed)} bytes "
		f"({100.0 * len(compressed) / len(bundle):.1f}% of raw)")


if __name__ == "__main__":
	sys.exit(main())
